# A vector with the information of what data to force download
# possible values are: (empty, default), "dtm", "soil", "adm_borders", "clc", "forinv", "clim_h", "clim_f", "co2_conc_h", "co2_conc_f"
force_download: []
# A vector with the information of which parts of ML workflow to force retrain
# possible values are: (empty, default), "tree_volumes", "ae_climh", "growth"
force_ml_train: []
# Other processing "force" options
# possible values are: (empty, default), "ing_points", "prediction_hist_tree_volumes", "xclimh" , "xclimf_reduced", "xfixedpx_reduced"
force_other: []


data_sources:
  dtm_url: "https://geodata.ucdavis.edu/climate/worldclim/2_1/base/wc2.1_30s_elev.zip"
  soil_ph_url: "https://esdac.jrc.ec.europa.eu/wyz_856/_33_GSM/${VAR}_Extra.zip"
  soil_chem_url: "https://esdac.jrc.ec.europa.eu/public_path/shared_folder/dataset/60/${VAR}.zip"
  soil_oth_url: "https://esdac.jrc.ec.europa.eu/wyz_856/_24_DER/STU_EU_Layers.zip"
  soil_ph_vars: ["Clay","Silt","Sand","CoarseFragments","BulkDensity","TextureUSDA","AWC"]
  soil_chem_vars: ["pH_H2O","pH_CaCl","CEC","Caco3","CN","N","P","K","pH_H2O_ratio_Cacl"]
  soil_oth_vars: ["STU_EU_DEPTH_ROOTS", "STU_EU_T_CLAY", "STU_EU_S_CLAY", "STU_EU_T_SAND", "STU_EU_S_SAND", "STU_EU_T_SILT", "STU_EU_S_SILT", "STU_EU_T_OC", "STU_EU_S_OC", "STU_EU_T_BD", "STU_EU_S_BD", "STU_EU_T_GRAVEL", "STU_EU_S_GRAVEL", "SMU_EU_T_TAWC", "SMU_EU_S_TAWC", "STU_EU_T_TAWC", "STU_EU_S_TAWC"]
  soil_texture_n_classes: 12
  #admin_borders_sources: ["https://github.com/wmgeolab/geoBoundaries/raw/v6.0.0/releaseData/gbOpen/FRA/ADM1/geoBoundaries-FRA-ADM1.geojson?download="]
  admin_borders_sources: [
    "https://github.com/wmgeolab/geoBoundaries/raw/v6.0.0/releaseData/gbOpen/FRA/ADM1/geoBoundaries-FRA-ADM1.dbf?download=",
    "https://github.com/wmgeolab/geoBoundaries/raw/v6.0.0/releaseData/gbOpen/FRA/ADM1/geoBoundaries-FRA-ADM1.prj?download=",
    "https://github.com/wmgeolab/geoBoundaries/raw/v6.0.0/releaseData/gbOpen/FRA/ADM1/geoBoundaries-FRA-ADM1.shp?download=",
    "https://github.com/wmgeolab/geoBoundaries/raw/v6.0.0/releaseData/gbOpen/FRA/ADM1/geoBoundaries-FRA-ADM1.shx?download="
  ]
  admin_borders_input_crs: 4326
  # Corine Land Cover 2018 V2020_20u1 vector (25 ha/100 m):
  # - source: https://land.copernicus.eu/en/products/corine-land-cover/clc2018
  # - DOI: https://doi.org/10.2909/71c95a07-e296-44fc-b22b-415f42acfdf0
  # Consider also:
  # - Land cover classification gridded maps world (300m): https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-land-cover?tab=overview
  # - CLC+ (10m, new classification):   
  clc_url: "https://zenodo.org/records/11549846/files/U2018_CLC2018_V2020_20u1.gpkg?download=1" # "https://nc.beta-lorraine.fr/s/9NrqQBmR5ib2wmd/download"
  # Forest inventory data: 
  # https://inventaire-forestier.ign.fr/dataIFN/
  forest_inventory_url: "https://inventaire-forestier.ign.fr/dataifn/data/export_dataifn_2005_2023.zip"
  forest_inventory_cres_epsg_id:  2154

  clim:
    # units: kg/m² (~mm), K, K, K
    vars: ["pr","tas","tasmax","tasmin"]
    # Trasnformation functions can be used to either correct a known model bias or (like in this case) to align the variables over the same unit
    transformations_h:
      pr:  "x -> x/100"
      tas: "x -> x/10"
      tasmax: "x -> x/10"
      tasmin: "x -> x/10"
    transformations_f:
    hist_years: [1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018]
    hist_base_url: "https://os.zhdk.cloud.switch.ch/chelsav2/GLOBAL/monthly/${VAR}/CHELSA_${VAR}_${MMONTH}_${YEAR}_V.2.1.tif"
    fut_base_path: "CHELSA_${INSTITUTION_ID}_${SOURCE_ID}_${VAR}_${EXPERIMENT_ID}_${MEMBER_ID}_${FEFPS}_${FEFPE}.nc"
    activity_id: "ScenarioMIP" 
    table_id:      "Amon"
    fixed_climate: true 
    # Standard ssp scenarios: 126, 245, 370 and 585. See https://www.dkrz.de/en/communication/climate-simulations/cmip6-en/the-ssp-scenarios
    experiment_id: "ssp126"
    experiment_id_extreme: "ssp585"
    institution_id: "MPI-M" 
    source_id: "MPI-ESM1-2-LR" 
    member_id: "r1i1p1f1"
    refps: "1981-01-15"
    refpe: "2010-12-15"
    fefps: "2015-01-01"
    fefpe: "2100-12-31"
    # Climatic AE parameters
    ae_nyears: 5
    ae_nsample: 300000
    ae_base_nepochs: 10
    ae_max_ntrains: 100
    ae_hidden_layer_size: 600
    ae_encoded_size: 6
  
  # See also:
  # - https://greenhousegases.science.unimelb.edu.au/#!/view
  # - https://gmd.copernicus.org/articles/13/3571/2020/
  # - https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_annmean_mlo.txt
  co2_conc_url: "https://raw.githubusercontent.com/SantanderMetGroup/wrf-ghg-files/refs/heads/master/CAMtr_volume_mixing_ratio.${SSP_SCENARIO}"

px_fixed_data:
    ae_maxntrain: 100000
    ae_base_nepochs: 10
    ae_max_ntrains: 100
    ae_hidden_layer_size: 300
    ae_encoded_size: 6

ign_data:
  genders_broadleaves: ["Acer", "Aesculus", "Ailanthus", "Alnus", "Arbutus", "Betula", "Broussonetia", "Buxus", "Carpinus", "Castanea", "Catalpa", "Celtis", "Ceratonia", "Cercis", "Citrus", "Cornus", "Corylus", "Crataegus", "Cupressus", "Cydonia", "Diospyros", "Elaeagnus", "Erica", "Eucalyptus", "Euonymus", "Fagus", "Ficus", "Frangula", "Fraxinus", "Ilex", "Juglans", "Laburnum", "Laurus", "Liquidambar", "Liriodendron", "Maclura", "Malus", "Morus", "Olea", "Ostrya", "Paulownia", "Phillyrea", "Pistacia", "Platanus", "Populus", "Prunus", "Pyrus", "Quercus", "Rhamnus", "Rhus", "Robinia", "Salix", "Sambucus", "Sorbus", "Tamarix", "Tilia", "Ulmus", "Vachellia"]
  genders_coniferous: ["Abies", "Casuarina", "Cedrus", "Chamaecyparis", "Cryptomeria", "Cupressus", "Juglans", "Juniperus", "Larix", "Picea", "Pinus", "Pseudotsuga", "Pyrus", "Sequoia", "Sequoiadendron", "Taxodium", "Taxus", "Thuja", "Tsuga"]
  nsample_v_imputation: 1000

growth_model_training:
  max_train_attempts: 200
  acceptable_mre_val: 0.385 # 0.38
  vol_growth_computation_adj_coeff: 0.001 # for comutational reasons to match orders of magnitude
  n_models: 2

ftypes: ["br_HF", "br_COP", "br_MIX", "mixsp_HF", "mixsp_MIX", "con_HF"]